variables:
  DOCKER_DRIVER: overlay2
  DOCKERHUB_REPO_NAME: docker-buildx-qemu
  QUAY_REPO_NAME: docker-buildx-qemu
  ENABLE_ARM64: 'true'

include:
  - project: 'ix.ai/ci-templates'
    file: '/common.yml'
